### ISSUE TITLE
节点管理API开发

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-apis#13]
- [ ] 组织下节点列表查询
- [ ] 组织下节点过滤
- [ ] 组织下新建节点

**Comment by bjwswang** [comment]
## 1. 节点列表查询

> NOTE: 选定某个组织 {org_name}

```sh
kubectl get ibppeers -n {org_name}
```

## 2. 节点过滤

> Note: 基于 `ibppeer.name`进行过滤


## 3. 新建节点

> NOTE: 选定某个组织 {org_name}

参考:  
- [完整yaml](https://github.com/bestchains/fabric-operator/blob/main/config/samples/peers/ibp.com_v1beta1_peer_org1peer1.yaml)
- [脚本实现](https://github.com/bestchains/fabric-operator/blob/main/config/samples/example-test.sh#L442)

需修改参数的详解: 
1. 获取组织对应的CA connecition profile，并解析获取所需内容

```sh
kubectl get cm -n {org_name} {org_name}-connection-profile
```
所需内容:
- [`tls.cacert`](https://github.com/bestchains/fabric-operator/blob/main/config/samples/peers/ibp.com_v1beta1_peer_org1peer1.yaml#L39) :  `jq -r '.tls.cert'`
- [`cahost`] :  1. `jq -r 'endpoints.api'`  2. 获取host
- [`caport`] : `jq -r 'endpoints.api'` 2. 获取端口号

**Comment by dayuy** [comment]
2.24 补充字段：
1. 组织详情：「加入的通道」
2. 节点管理：「加入的网络」、「加入的通道」

**Comment by dayuy** [comment]
1. 新增节点数量 createIbppeer($org: String!, $count: Float)
