### ISSUE TITLE
开源区块链浏览器改造

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-apis#28]
项目地址: https://github.com/bestchains/blockchain-explorer
公共服务地址:  http://47.243.122.42:8080/  exploreradmin/exploreradminpw
改造评估List:

- [ ] IAM是否可集成
- [ ] 页面改造难度、工作量

**Comment by Carrotzpc** [comment]
初步看了下：
- 关于 IAM 集成，blockchain-explorer 使用的是 [passport](https://www.passportjs.org/) 的本地登录模式，可以修改下相关代码，集成 oidc 的登录：
https://github.com/bestchains/blockchain-explorer/blob/main/app/Explorer.ts#L112
- 关于页面改造，blockchain-explorer 前端使用的 material-ui，我们用的 antd，风格和交互差异都比较大，统一风格和交互工作量比较大，可以考虑基于 material-ui 美化一下，尽量贴近我们的风格
- 关于接入微前端改造，需要 @zggmd 评估一下

**Comment by bjwswang** [comment]
related issue in fabric-operator to support this blockchain explorer
https://github.com/bestchains/fabric-operator/issues/172

**Comment by bjwswang** [comment]
closed as we decide to devlop by our own
