### ISSUE TITLE
合约管理：合约状态非正常情况，不允许点击部署

### ISSUE THREAD

**Issue by 0xff-dev** [bestchains/bc-apis#54]
合约管理：合约状态非正常情况，不允许点击部署。

**Comment by dayuy** [comment]
Chaincodebuild.status === 'Created' && !!Chaincodebuild.pipelineImageUrl @Jandiasnow

**Comment by dayuy** [comment]
@Jandiasnow  不用判断pipelineImageUrl了，直接按照👇
Chaincodebuild.status === 'Created'  显示「正常」，可以点击部署
Chaincodebuild.status === 'Deploying' 显示「部署中」
