### ISSUE TITLE
组织名称：组织名称规则不正确

### ISSUE THREAD

**Issue by 0xff-dev** [bestchains/bc-apis#55]
组织名称：组织名称规则不正确。

**Comment by dayuy** [comment]
组织名称，规则：小写字母、数字、“-”，开头和结尾只能是字母或数字`[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`'
@Jandiasnow
